engines:
  duplication:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,controversial,design,naming,unusedcode"
  phan:
    enabled: true
exclude_paths:
- "tests/"
ratings:
  paths:
  - "**.php"